### ISSUE TITLE
:hammer_and_wrench: Show clock

### ISSUE THREAD

**Issue by uhooi** [MunifTanjim/nougat.nvim#52]
### Did you check the docs and existing issues?

- [X] I am using latest nougat.nvim
- [X] I have read all the nougat.nvim docs
- [X] I have searched the existing issues of nougat.nvim

### Problem

I want to display a clock, but it is not updating.

nougat.nvim config

```lua
-- datetime {{{
local datetime = (function()
  local item = Item {
    sep_left = sep.left_half_circle_solid(true),
    content = {
      Item {
        hl = { bg = color.green, fg = color.bg },
        content = vim.fn.strftime('%H:%M'), -- FIXME: Not refreshing
      },
    },
    sep_right = sep.right_half_circle_solid(true),
  }

  return item
end)()
-- }}}

-- statusline {{{
local stl = Bar('statusline')
stl:add_item(datetime)
bar_util.set_statusline(stl)
-- }}}
```

### Solution

Clock is refreshed.

**Comment by MunifTanjim** [comment]
You're assigning a string as `content`. You need to make it a function.

```lua
content = function()
  return vim.fn.strftime('%H:%M')
end,
```

**Comment by uhooi** [comment]
Oh.. the clock has been refreshed, thank you!
https://github.com/uhooi/dotfiles/commit/14fd18b4be38eb04e6532fa0cc521ffbe22ea15d
