### ISSUE TITLE
Add filetype icon for filetype component

### ISSUE THREAD

**Issue by linrongbin16** [MunifTanjim/nougat.nvim#77]
### Did you check the docs and existing issues?

- [X] I am using latest nougat.nvim
- [X] I have read all the nougat.nvim docs
- [X] I have searched the existing issues of nougat.nvim

### Problem

https://github.com/MunifTanjim/nougat.nvim/blob/main/lua/nougat/nut/buf/filetype.lua, the filetype component don't have 'format' function, which cannot use devicons to show the colored file type icons.

lualine have filetype icon:

![SAVE_20240102_180639](https://github.com/MunifTanjim/nougat.nvim/assets/6496887/b42d790d-026a-49e3-ad29-6be358226278)

### Solution

add 'format' function to allow user do customization.

**Comment by linrongbin16** [comment]
I think I know now.

**Comment by MunifTanjim** [comment]
Hey @linrongbin16 , I think this is worth having in the built-in `filetype` component. 

Not sure why you closed the issue... Did you think of any alternatives? 🤔

**Comment by linrongbin16** [comment]
> Hey @linrongbin16 , I think this is worth having in the built-in `filetype` component.
> 
> Not sure why you closed the issue... Did you think of any alternatives? 🤔

I read the item.content here: https://github.com/MunifTanjim/nougat.nvim/tree/main/lua/nougat/item#content, and item.type here: https://github.com/MunifTanjim/nougat.nvim/tree/main/lua/nougat/item#type.

I think if I set type to 'lua_expr' and content to be a lua function, so I can render the icon in the lua function? 

I didn't test it yet.

**Comment by MunifTanjim** [comment]
[`nut.buf.filetype`](https://github.com/MunifTanjim/nougat.nvim/blob/main/lua/nougat/nut/buf/filetype.lua) is actually a wrapper around [`nougat.item`](https://github.com/MunifTanjim/nougat.nvim/tree/main/lua/nougat/item). `nut.buf.filetype` does not pass everything to `nougat.item`, as you can see here: https://github.com/MunifTanjim/nougat.nvim/blob/6024f7558fe4759ce81723fd770a6abe5ceb7010/lua/nougat/nut/buf/filetype.lua#L15-L30

`content` and `type` is always hardcoded.

What you want to do is this:

```lua
local Item = require("nougat.item")

stl:add_item(Item({
    hl = { bg = color.bg1 },
    sep_left = sep.left_lower_triangle_solid(true),
    prefix = " ",
    suffix = " ",
    content = function(ctx)
        message.info("|nougat.filetype| ctx:%s", vim.inspect(ctx))
        local ft = vim.bo.filetype
        local ok, devicons = pcall(require, "nvim-web-devicons")
        if not ok then
            return ft or ""
        end
        local icon_text, icon_color =
            devicons.get_icon_cterm_color_by_filetype(ft)
        message.info(
            "|nougat.filetype| ctx:%s, icon_text:%s, icon_color:%s",
            vim.inspect(ctx),
            vim.inspect(icon_text),
            vim.inspect(icon_color)
        )
        return icon_text .. " " .. ft
    end,
}))
```

**Comment by linrongbin16** [comment]
> [`nut.buf.filetype`](https://github.com/MunifTanjim/nougat.nvim/blob/main/lua/nougat/nut/buf/filetype.lua) is actually a wrapper around [`nougat.item`](https://github.com/MunifTanjim/nougat.nvim/tree/main/lua/nougat/item). `nut.buf.filetype` does not pass everything to `nougat.item`, as you can see here:
> 
> https://github.com/MunifTanjim/nougat.nvim/blob/6024f7558fe4759ce81723fd770a6abe5ceb7010/lua/nougat/nut/buf/filetype.lua#L15-L30
> 
> `content` and `type` is always hardcoded.
> 
> > My LuaLs diagnostics shows there're type check errors, so I guess the 'type' and 'content' option are not accept by 'filetype' component:
> 
> Yep, that's right. The built-in `nut.buf.filetype` component is not very configurable right now.
> 
> What you want to do is this:
> 
> ```lua
> local Item = require("nougat.item")
> 
> stl:add_item(Item({
>     hl = { bg = color.bg1 },
>     sep_left = sep.left_lower_triangle_solid(true),
>     prefix = " ",
>     suffix = " ",
>     content = function(_, ctx)
>         message.info("|nougat.filetype| ctx:%s", vim.inspect(ctx))
>         local ft = vim.bo.filetype
>         local ok, devicons = pcall(require, "nvim-web-devicons")
>         if not ok then
>             return ft or ""
>         end
>         local icon_text, icon_color =
>             devicons.get_icon_cterm_color_by_filetype(ft)
>         message.info(
>             "|nougat.filetype| ctx:%s, icon_text:%s, icon_color:%s",
>             vim.inspect(ctx),
>             vim.inspect(icon_text),
>             vim.inspect(icon_color)
>         )
>         return icon_text .. " " .. ft
>     end,
> }))
> ```

thank, will try later!

**Comment by MunifTanjim** [comment]
Example usage for the newly added `filetype_icon`:

```lua
local nut = {
  buf = {
    filetype = require("nougat.nut.buf.filetype").create,
    filetype_icon = require("nougat.nut.buf.filetype_icon").create,
  },
}

stl:add_item({
  hl = { bg = color.bg1 },
  prefix = " ",
  content = {
    nut.buf.filetype_icon({ suffix = " " }),
    nut.buf.filetype({}),
  },
  suffix = " ",
})
```
